---
bootstrap_user: "{{ ansible_user_id }}"
bootstrap_home: "{{ ansible_env.HOME | default('/home/' + bootstrap_user) }}"

nvim_packages:
  - neovim
  - git
  - curl
  - ripgrep
  - fd-find
  - wl-clipboard
  - build-essential
  - tree-sitter
  - nodejs
  - npm

lazyvim_repo: "https://github.com/LazyVim/starter"
nvim_config_dir: "{{ bootstrap_home }}/.config/nvim"

lazyvim_remove_git: true
lazyvim_force: false

fd_link_enable: true
fd_link_path: "{{ bootstrap_home }}/.local/bin/fd"

nvim_alias_enable: true
nvim_alias_dir: "{{ bootstrap_home }}/.local/bin"
nvim_alias_names:
  - vim
  - vi
